select
    ID                              AS ID
    ,FIRSTACTIVEDAY                  AS FIRSTACTIVEDAY
    ,SM_DEVICE                       AS SM_DEVICE
    ,BILLING_GROUP_ID                AS BILLING_GROUP_ID
    ,BIDPOINTS                       AS BIDPOINTS
    ,CUSTOM1                         AS CUSTOM1
    ,BILLING_LICENSE_ID              AS BILLING_LICENSE_ID
    ,DEFAULTPAYRATEBYUNIT            AS DEFAULTPAYRATEBYUNIT
    ,WEEKLYHOURS                     AS WEEKLYHOURS
    ,NOTES                           AS NOTES
    ,PERCENT_EMPLOYED                AS PERCENT_EMPLOYED
    ,CUSTOM4                         AS CUSTOM4
    ,OLDCOMPACTNAME                  AS OLDCOMPACTNAME
    ,ENABLED                         AS ENABLED
    ,DEFAULTPAYRATE                  AS DEFAULTPAYRATE
    ,DESIREDUNITTYPE                 AS DESIREDUNITTYPE
    ,CUSTOM3                         AS CUSTOM3
    ,EMPLOYEENUMBER                  AS EMPLOYEENUMBER
    ,USERID                          AS USERID
    ,HIREDATE                        AS HIREDATE
    ,CUSTOM2                         AS CUSTOM2
    ,PRINT_NAME                      AS PRINT_NAME
    ,LASTACTIVEDAY                   AS LASTACTIVEDAY
    ,LAST_NAME                       AS LAST_NAME
    ,DESIREDUNITS                    AS DESIREDUNITS
    ,PROFESSION                      AS PROFESSION
    ,HOME_PHONE                      AS HOME_PHONE
    ,GROUPID                         AS GROUPID
    ,LASTMODIFIEDDATE                AS LASTMODIFIEDDATE
    ,LASTMODIFIEDBY                  AS LASTMODIFIEDBY
    ,ANY_ROLE                        AS ANY_ROLE
    ,BUSINESS_PHONE                  AS BUSINESS_PHONE
    ,SHIFT                           AS SHIFT
    ,TITLE                           AS TITLE
    ,DEPARTMENT                      AS DEPTID
    ,PAGER                           AS PAGER
    ,FIRST_NAME                      AS FIRST_NAME
    ,MIDDLE_NAME                     AS MIDDLE_NAME
    ,SENIORITYDATE                   AS SENIORITYDATE
    ,EMAIL_TO_PAGER                  AS EMAIL_TO_PAGER
    ,E_MAIL                          AS E_MAIL
    ,ADDRESS                         AS ADDRESS
    ,UNIQUEID                        AS UNIQUEID
    ,JOBCODE                         AS JOBCODE
    ,DISPLAY_NAME                    AS DISPLAY_NAME
    ,STAFFSCHEDULED                  AS STAFFSCHEDULED
    ,HISTORICALTALLY                 AS HISTORICALTALLY
    ,PERSONA_ID                      AS PERSONA_ID
    ,PAGER_PROVIDER                  AS PAGER_PROVIDER
    ,CELL_PHONE                      AS CELL_PHONE
    ,COMPACT_NAME                    AS COMPACT_NAME
    ,ALL_SCHEDULES                   AS ALL_SCHEDULES
    ,SYSTEMSTAFF                     AS SYSTEMSTAFF
    ,AUTOGENERATED                   AS AUTOGENERATED
    ,TITLE_ID                        AS TITLE_ID
    ,SM_ACCOUNT                      AS SM_ACCOUNT
    ,PERSONNEL_TYPE_ID               AS PERSONNEL_TYPE_ID
    ,_FIVETRAN_DELETED               AS _FIVETRAN_DELETED
    ,_FIVETRAN_SYNCED                AS _FIVETRAN_SYNCED
    ,NOTIFICATION_EMAIL              AS NOTIFICATION_EMAIL
    ,NATIONAL_PROVIDER_IDENTIFIER    AS NATIONAL_PROVIDER_IDENTIFIER

from {{ source('prisma', 'personnel') }}

{% if is_incremental() %}

where _FIVETRAN_SYNCED > (select max(_FIVETRAN_SYNCED) from {{ this }} )

{% endif %}