lb_prisma:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"

      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"

      warehouse: DBT_LB_WH
      role: "{{ env_var('DBT_ROLE') }}"
      database: Metadata
      schema: Public
      threads: 16
