# ==================
# Project Details
# ==================
name: 'lb_prisma'
version: '1.0.0'
config-version: 2
profile: 'lb_prisma'

# ==================
# File Path Configs
# ==================
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  
clean-targets: ["target"]

# ==================
# Model Configs
# ==================
models:
  +materialized: incremental
  lb_prisma:
    staging:
      database: lb_prod
      schema: lb_prismahealth
    prisma:
      database: data_sharing_prod
      schema: prisma_lb_public

# ==================
# Model Tests
# ==================
tests:
  store_failures: false